// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dajlvwnsmjyqbnsbgryo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhamx2d25zbWp5cWJuc2JncnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMzc3MjQsImV4cCI6MjA3MTYxMzcyNH0.CZP1EPvSCo8qrPjAqLovsT_dDIrV06Mkq1zoneWED-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});